[package]
name = "maildir-notify-daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hotwatch = "0.4"
mailparse = "0.13"
notify-rust = "4.8"

[features]
